export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const GET_TOP_CATEGORIES_SUCCESS="GET_TOP_CATEGORIES_SUCCESS"

export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const ADD_TO_PRODUCT_DETAIL="ADD_TO_PRODUCT_DETAIL"

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const SUM_PRICE="SUM_PRICE"

export const ADD_TO_FAVORITE="ADD_TO_FAVORITE"
export const REMOVE_FROM_FAVORITE="REMOVE_FROM_FAVORITE"

export const USER_LOGIN="USER_LOGIN_SUCCESS"
export const USER_SIGN_UP="USER_SING_UP_SUCCESS"