server:
  port: 8502

spring:
  application:
    name: product-api
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:./productApi/devdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        javax:
          persistence:
            validation:
              mode: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}