server:
  port: 8503

spring:
  application:
    name: topcategory-service
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}
  datasource:
    url: jdbc:h2:./topCategory-service/devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}